  
version: '3'

services:
  server:
    image: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./php:/var/www/html"
    ports:
      - "8080:80"
    depends_on:
      - php

  db:
    image: mysql:8
    volumes:
     - ./mysql:/var/lib/mysql/
    environment:
     POSTGRES_USER: root
     POSTGRES_PASSWORD: root
     POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    user: root
    ports:
      - "3306:3306"

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - "./php:/var/www/html"
    depends_on:
      - db
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 10080:80